### ISSUE TITLE
MRC training with custom model but HF `roberta-base` tokenizer

### ISSUE THREAD

**Issue by PauToroIsaza** [primeqa/primeqa#436]
When I try this script with a custom model but `roberta-base` tokenizer, the datasets get tokenized but during training I get an error. 

The script works if I read in a custom tokenizer trained on some other data.

Script:
```
#!/usr/bin/env bash                                                                                                                                                               
set -xeo pipefail

export PYTHONPATH="${PYTHONPATH}:/mnt/ptoroisaza/primeqa"

python /mnt/ptoroisaza/primeqa/primeqa/mrc/run_mrc.py \
--model_name_or_path /mnt/shared/models/fm/Slack_FM_2 \
--tokenizer_name roberta-base \
--config_name /mnt/shared/models/fm/Slack_FM_2/config.json \
--train_file /mnt/ptoroisaza/data/finetuning/TechQA/train_Q_A.jsonl \
--eval_file /mnt/ptoroisaza/data/finetuning/TechQA/dev_Q_A.jsonl \
--data_file_format json \
--preprocessor primeqa.mrc.processors.preprocessors.squad.SQUADPreprocessor \
--postprocessor primeqa.mrc.processors.postprocessors.squad.SQUADPostProcessor \
--eval_metrics SQUAD \
--output_dir /mnt/ptoroisaza/training \
--learning_rate "4e-5" --do_train --do_eval --per_device_train_batch_size 8 --per_device_eval_batch_size 8 \
--gradient_accumulation_steps 2 --warmup_ratio 0.1 --weight_decay 0.1 --save_steps 50000 \
--num_train_epochs 5 \
--max_seq_length 512 \
--overwrite_output_dir --evaluation_strategy no --overwrite_cache
```

Error:
```
Traceback (most recent call last):
  File "/mnt/ptoroisaza/primeqa/primeqa/mrc/run_mrc.py", line 550, in <module>
    main()
  File "/mnt/ptoroisaza/primeqa/primeqa/mrc/run_mrc.py", line 489, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 1501, in train
    return inner_training_loop(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 1749, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 2508, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 2540, in compute_loss
    outputs = model(**inputs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/ptoroisaza/primeqa/primeqa/mrc/models/task_model.py", line 80, in forward
    outputs = self.model_(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 846, in forward
    encoder_outputs = self.encoder(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 520, in forward
    layer_outputs = layer_module(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 447, in forward
    layer_output = apply_chunking_to_forward(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/pytorch_utils.py", line 246, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 460, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 373, in forward
    hidden_states = self.LayerNorm(hidden_states + input_tensor)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by avisil** [comment]
What happens when you try this on CPU ? (since the error mainly points to a CUDA error)

**Comment by avisil** [comment]
@PauToroIsaza is this resolved?

**Comment by PauToroIsaza** [comment]
No, sorry haven't been able to get back to this because of strict deadlines for other projects.
